-- Nouveaux jeux Game Gear à ajouter

INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Adventures of Batman _ Robin, The', 'Adventures of Batman _ Robin, The');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Aladdin (Japan)', 'Aladdin (Japan)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Aladdin (World)', 'Aladdin (World)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Alien 3 (Japan)', 'Alien 3 (Japan)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Alien 3 (World)', 'Alien 3 (World)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Alien Syndrome (Japan)', 'Alien Syndrome (Japan)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Asterix and the Great Rescue Europe En Fr De Es (It)', 'Asterix and the Great Rescue Europe En Fr De Es (It)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Asterix and the Great Rescue', 'Asterix and the Great Rescue');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Ax Battler - A Legend of Golden Axe', 'Ax Battler - A Legend of Golden Axe');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Buster Fight Japan En (Ja)', 'Buster Fight Japan En (Ja)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Castle of Illusion Starring Mickey Mouse', 'Castle of Illusion Starring Mickey Mouse');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Daffy Duck in Hollywood Europe Brazil En Fr De Es (It)', 'Daffy Duck in Hollywood Europe Brazil En Fr De Es (It)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Desert Strike Europe En Fr De (Es)', 'Desert Strike Europe En Fr De (Es)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Dragon Crystal - Tsurani no Meikyuu', 'Dragon Crystal - Tsurani no Meikyuu');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Earthworm Jim', 'Earthworm Jim');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Ernie Els Golf Europe En Fr De Es (It)', 'Ernie Els Golf Europe En Fr De Es (It)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Fantastic Dizzy Usa Europe En Fr De Es (It)', 'Fantastic Dizzy Usa Europe En Fr De Es (It)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Fatal Fury Special', 'Fatal Fury Special');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Fifa Soccer 96 Usa Europe En Fr De (Es)', 'Fifa Soccer 96 Usa Europe En Fr De (Es)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Fred Couples Golf', 'Fred Couples Golf');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Indiana Jones and the Last Crusade', 'Indiana Jones and the Last Crusade');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Jungle Book, The', 'Jungle Book, The');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Land of Illusion Starring Mickey Mouse', 'Land of Illusion Starring Mickey Mouse');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Lucky Dime Caper Starring Donald Duck, The', 'Lucky Dime Caper Starring Donald Duck, The');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Markos Magic Football Europe En Fr De (Es)', 'Markos Magic Football Europe En Fr De (Es)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Mighty Morphin Power Rangers - The Movie', 'Mighty Morphin Power Rangers - The Movie');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('NBA Action Starring David Robinson', 'NBA Action Starring David Robinson');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Nazo Puyo 2', 'Nazo Puyo 2');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Olympic Gold Europe En Fr De Es It Nl (Pt)', 'Olympic Gold Europe En Fr De Es It Nl (Pt)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Olympic Gold Japan Usa Brazil En Fr De Es It Nl (Pt)', 'Olympic Gold Japan Usa Brazil En Fr De Es It Nl (Pt)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Olympic Gold Taiwan En Fr De Es It Nl Pt Sv Unl', 'Olympic Gold Taiwan En Fr De Es It Nl Pt Sv Unl');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Ottifants the Europe En Fr De Es (It)', 'Ottifants the Europe En Fr De Es (It)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('OutRun Europa', 'OutRun Europa');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Puyo Puyo Japan En (Ja)', 'Puyo Puyo Japan En (Ja)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Riddick Bowe Boxing', 'Riddick Bowe Boxing');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Scratch Golf', 'Scratch Golf');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Shinobi II - The Silent Fury', 'Shinobi II - The Silent Fury');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Smurfs the Europe En Fr De (Es)', 'Smurfs the Europe En Fr De (Es)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Sonic The Hedgehog - Triple Trouble', 'Sonic The Hedgehog - Triple Trouble');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Sonic The Hedgehog 2', 'Sonic The Hedgehog 2');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Streets of Rage 2', 'Streets of Rage 2');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Striker Europe En Fr De Es (It)', 'Striker Europe En Fr De Es (It)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Super Kick Off Europe En Fr De Es It Nl (Pt)', 'Super Kick Off Europe En Fr De Es It Nl (Pt)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Sylvan Tale', 'Sylvan Tale');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Tails Skypatrol Jsh Sega Sims Japantr (Pt)', 'Tails Skypatrol Jsh Sega Sims Japantr (Pt)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Taisen Mahjong HaoPai 2', 'Taisen Mahjong HaoPai 2');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Taito Chase H Q Japan (En)', 'Taito Chase H Q Japan (En)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Tintin in Tibet Europe En Fr De Es Nl Sv', 'Tintin in Tibet Europe En Fr De Es Nl Sv');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Tom and Jerry the Movie Usa Europe En (Ja)', 'Tom and Jerry the Movie Usa Europe En (Ja)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('Ultimate Soccer Japan Europe Brazil En Fr De Es (It)', 'Ultimate Soccer Japan Europe Brazil En Fr De Es (It)');
INSERT INTO game_gear_games (name, ROM_ID) VALUES ('alien-syndrome-PAL', 'alien-syndrome-PAL');
