-- ══════════════════════════════════════════════════════════════════════════════
-- SUPPRESSION JEUX SANS IMAGES - GAME GEAR
-- Pour atteindre 100% de correspondance
-- Total suppressions: 162
-- ══════════════════════════════════════════════════════════════════════════════

DELETE FROM game_gear_games WHERE id = 24; -- Aladdin [tr pt ERTrans](Alt 1)[pt-br]
DELETE FROM game_gear_games WHERE id = 1050; -- alien-syndrome-PAL
DELETE FROM game_gear_games WHERE id = 35; -- Arena (EU-US)[tr fr GenerationIX]
DELETE FROM game_gear_games WHERE id = 40; -- Asterix and the Great Rescue (Europe) (En,Fr,De,Es,It)
DELETE FROM game_gear_games WHERE id = 47; -- Asterix and the Great Rescue (USA, Brazil) (En)
DELETE FROM game_gear_games WHERE id = 52; -- Ax Battler - A Legend of Golden Axe (USA, Europe, Brazil) (En)
DELETE FROM game_gear_games WHERE id = 55; -- Ax Battler - A Legend of Golden Axe v2.4 [tr es pkt][100%]
DELETE FROM game_gear_games WHERE id = 56; -- Ax Battler - A Legend of Golden Axe v2.4 [tr fr Rysley][2006-09-26]
DELETE FROM game_gear_games WHERE id = 57; -- Ax Battler - A Legend of Golden Axe v2.4 [tr fr](Alt 1)
DELETE FROM game_gear_games WHERE id = 69; -- Batman Forever (World)
DELETE FROM game_gear_games WHERE id = 71; -- Batman Returns [t +1 Mystic]
DELETE FROM game_gear_games WHERE id = 73; -- Battleship - The Classic Naval Combat Game (Mindscape) (USA)
DELETE FROM game_gear_games WHERE id = 74; -- Battleship - The Classic Naval Combat Game (Mindscape) (USA)[b2]
DELETE FROM game_gear_games WHERE id = 75; -- Battleship - The Classic Naval Combat Game (Mindscape) (USA)[b3]
DELETE FROM game_gear_games WHERE id = 76; -- Battleship - The Classic Naval Combat Game (Mindscape) (USA)[b4]
DELETE FROM game_gear_games WHERE id = 105; -- Bishoujo Senshi Sailor Moon S (Japan)
DELETE FROM game_gear_games WHERE id = 107; -- Bishoujo Senshi Sailor Moon S (Japan)[b3]
DELETE FROM game_gear_games WHERE id = 124; -- Bram Stoker''s Dracula (Europe)
DELETE FROM game_gear_games WHERE id = 131; -- Buster Fight (Japan) (En,Ja)
DELETE FROM game_gear_games WHERE id = 140; -- Castle of Illusion Starring Mickey Mouse (USA, Europe, Brazil) (En)
DELETE FROM game_gear_games WHERE id = 183; -- Chuck Rock [t +1 Mystic]
DELETE FROM game_gear_games WHERE id = 184; -- Chuck Rock [t +1 Mystic][o]
DELETE FROM game_gear_games WHERE id = 180; -- Chuck Rock II - Son of Chuck (Europe, Brazil) (En)
DELETE FROM game_gear_games WHERE id = 190; -- Columns (USA, Europe, Brazil) (Rev 2)
DELETE FROM game_gear_games WHERE id = 197; -- Crystal Warriors (EU-US)[tr fr]
DELETE FROM game_gear_games WHERE id = 201; -- Daffy Duck in Hollywood (Europe, Brazil) (En,Fr,De,Es,It)
DELETE FROM game_gear_games WHERE id = 202; -- Daffy Duck in Hollywood (Probe - Sega) (M5)[b2]
DELETE FROM game_gear_games WHERE id = 203; -- Deep Duck Trouble Starring Donald Duck (Disney - Sega) (Japan) (en-ja)[t +1][infinite lives]
DELETE FROM game_gear_games WHERE id = 204; -- Deep Duck Trouble Starring Donald Duck (Disney - Sega)[t +1 Asgard][infinite lives]
DELETE FROM game_gear_games WHERE id = 213; -- Desert Strike (Europe) (En,Fr,De,Es)
DELETE FROM game_gear_games WHERE id = 221; -- Donald Duck no Yottsu no Hihou (Disney - Sega) (Japan)[t +1 Asgard][infinite lives]
DELETE FROM game_gear_games WHERE id = 222; -- Donald Duck no Yottsu no Hihou (Disney - Sega) (Japan)[t +1][infinite lives]
DELETE FROM game_gear_games WHERE id = 223; -- Donald no Magical World (Asia) (en-ja)[h][AKA Ronald in the Magical World]
DELETE FROM game_gear_games WHERE id = 224; -- Donald no Magical World (Asia) (en-ja)[t +1 Asgard][infinite lives][AKA Ronald in the Magical World]
DELETE FROM game_gear_games WHERE id = 232; -- Dragon - The Bruce Lee Story (Europe)
DELETE FROM game_gear_games WHERE id = 236; -- Dragon Crystal - Tsurani no Meikyuu (Japan) (Virtual Console)
DELETE FROM game_gear_games WHERE id = 246; -- Earthworm Jim (Eurocom - Playmates - Virgin) (Europe)[t +1][infinite health]
DELETE FROM game_gear_games WHERE id = 247; -- Earthworm Jim (Eurocom - Playmates - Virgin) (USA)[t]
DELETE FROM game_gear_games WHERE id = 248; -- Earthworm Jim (Europe)
DELETE FROM game_gear_games WHERE id = 253; -- Ecco the Dolphin (EU-US)[b2]
DELETE FROM game_gear_games WHERE id = 260; -- Empire Syndicate (Proto)[Chicago Syndicate]
DELETE FROM game_gear_games WHERE id = 263; -- Ernie Els Golf (Europe) (En,Fr,De,Es,It)
DELETE FROM game_gear_games WHERE id = 264; -- Eternal Legend (Japan)
DELETE FROM game_gear_games WHERE id = 278; -- Fantastic Dizzy (USA, Europe) (En,Fr,De,Es,It)
DELETE FROM game_gear_games WHERE id = 283; -- Fatal Fury Special (Europe)
DELETE FROM game_gear_games WHERE id = 284; -- Fatal Fury Special (SNK - Takara) (USA)[b2]
DELETE FROM game_gear_games WHERE id = 274; -- FIFA Soccer 96 (USA, Europe) (En,Fr,De,Es)
DELETE FROM game_gear_games WHERE id = 290; -- Fred Couples Golf (Japan)
DELETE FROM game_gear_games WHERE id = 304; -- GG Shinobi Part II, The - The Silent Fury (Japan)
DELETE FROM game_gear_games WHERE id = 306; -- GG Shinobi Part II, The - The Silent Fury [b3]
DELETE FROM game_gear_games WHERE id = 307; -- GG Shinobi Part II, The - The Silent Fury [b4]
DELETE FROM game_gear_games WHERE id = 330; -- Greendog [b2]
DELETE FROM game_gear_games WHERE id = 338; -- Head Buster (NCS) (Japan) (en-ja)[tr en Chris Covell][v0.99]
DELETE FROM game_gear_games WHERE id = 352; -- Indiana Jones and the Last Crusade (LucasArts - Tiertex Design Studio - U.S. Gold)[t +1 Mystic]
DELETE FROM game_gear_games WHERE id = 353; -- Indiana Jones and the Last Crusade (LucasArts - Tiertex Design Studio - U.S. Gold)[t]
DELETE FROM game_gear_games WHERE id = 354; -- Indiana Jones and the Last Crusade (USA, Europe, Brazil) (En)
DELETE FROM game_gear_games WHERE id = 363; -- James Pond II - Codename RoboCod (Europe)
DELETE FROM game_gear_games WHERE id = 369; -- Joe Montana Football (Japan, Brazil) (En) (Rev 1)
DELETE FROM game_gear_games WHERE id = 376; -- Jungle Book, The (Europe)
DELETE FROM game_gear_games WHERE id = 384; -- Kawasaki Superbike Challenge (Europe)
DELETE FROM game_gear_games WHERE id = 394; -- Land of Illusion Starring Mickey Mouse (Disney - Sega)[t +1 Mystic]
DELETE FROM game_gear_games WHERE id = 395; -- Land of Illusion Starring Mickey Mouse (USA, Europe, Brazil) (En)
DELETE FROM game_gear_games WHERE id = 409; -- Lion King, The (Europe)
DELETE FROM game_gear_games WHERE id = 412; -- Lion King, The (USA)[t +1 Mystic]
DELETE FROM game_gear_games WHERE id = 426; -- Lucky Dime Caper Starring Donald Duck, The (USA, Europe, Brazil) (En)
DELETE FROM game_gear_games WHERE id = 428; -- Lunar - Sanposuru Gakuen (Game Arts) (Japan)[tr en Aeon Genesis - Some Good Shit][v1.0]
DELETE FROM game_gear_games WHERE id = 436; -- Lunar - Sanposuru Gakuen (Game Arts) (Japan)[tr en]
DELETE FROM game_gear_games WHERE id = 433; -- Lunar - Sanposuru Gakuen (Game Arts) (Japan)[tr en](Alt 1)
DELETE FROM game_gear_games WHERE id = 434; -- Lunar - Sanposuru Gakuen (Game Arts) (Japan)[tr en](Alt 2)
DELETE FROM game_gear_games WHERE id = 435; -- Lunar - Sanposuru Gakuen (Game Arts) (Japan)[tr en](Alt 3)
DELETE FROM game_gear_games WHERE id = 438; -- Lunar - Sanposuru Gakuen (Game Arts) (Japan)[tr pt]
DELETE FROM game_gear_games WHERE id = 437; -- Lunar - Sanposuru Gakuen (Game Arts) (Japan)[tr pt](Alt 1)
DELETE FROM game_gear_games WHERE id = 443; -- Madden 96 (Black Pearl Software - Electronic Arts - Tiertex Design Studio)[b2]
DELETE FROM game_gear_games WHERE id = 462; -- Mappy (Japan)
DELETE FROM game_gear_games WHERE id = 465; -- Mappy (Namco) (Japan)[tr en Maxim][v1.0]
DELETE FROM game_gear_games WHERE id = 466; -- Mappy (Namco) (Japan)[tr en Maxim][v1.1]
DELETE FROM game_gear_games WHERE id = 467; -- Marble Madness (Atari - Tengen)[b2]
DELETE FROM game_gear_games WHERE id = 469; -- Marko''s Magic Football (Europe) (En,Fr,De,Es)
DELETE FROM game_gear_games WHERE id = 473; -- Mega Man (Capcom - U.S. Gold)[tr de Star-trans]
DELETE FROM game_gear_games WHERE id = 474; -- Mega Man (Capcom - U.S. Gold)[tr de Star-trans][v1.00]
DELETE FROM game_gear_games WHERE id = 483; -- Mickey Mouse no Castle Illusion (Japan) (en-ja)[h]
DELETE FROM game_gear_games WHERE id = 492; -- Mighty Morphin Power Rangers (USA, Europe)
DELETE FROM game_gear_games WHERE id = 505; -- Mortal Kombat [b2]
DELETE FROM game_gear_games WHERE id = 587; -- Nazo Puyo (Japan)
DELETE FROM game_gear_games WHERE id = 539; -- NBA Action Starring David Robinson (USA, Brazil) (En)
DELETE FROM game_gear_games WHERE id = 542; -- NBA Jam (USA) (Rev 1) (Putative Proto)
DELETE FROM game_gear_games WHERE id = 602; -- Olympic Gold (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv)
DELETE FROM game_gear_games WHERE id = 603; -- Olympic Gold (Japan, USA, Brazil) (En,Fr,De,Es,It,Nl,Pt,Sv)
DELETE FROM game_gear_games WHERE id = 604; -- Olympic Gold (Taiwan) (En,Fr,De,Es,It,Nl,Pt,Sv) (Unl)
DELETE FROM game_gear_games WHERE id = 605; -- Ottifants, The (Europe) (En,Fr,De,Es,It)
DELETE FROM game_gear_games WHERE id = 606; -- Out Run (Japan)[b2]
DELETE FROM game_gear_games WHERE id = 609; -- Out Run Europa (Probe - Sega - U.S. Gold) (USA)[tr pt]
DELETE FROM game_gear_games WHERE id = 611; -- OutRun (Europe, Brazil)
DELETE FROM game_gear_games WHERE id = 626; -- Paperboy (Atari - Tengen - Tiertex Design Studio)[t]
DELETE FROM game_gear_games WHERE id = 633; -- Pete Sampras Tennis (Europe)
DELETE FROM game_gear_games WHERE id = 635; -- Pete Sampras Tennis (USA, Europe)
DELETE FROM game_gear_games WHERE id = 617; -- PGA Tour Golf (USA) (Rev 1) (Putative Proto)
DELETE FROM game_gear_games WHERE id = 619; -- PGA Tour Golf II (Time Warner Interactive)[b2]
DELETE FROM game_gear_games WHERE id = 620; -- PGA Tour Golf II (Time Warner Interactive)[b3]
DELETE FROM game_gear_games WHERE id = 639; -- Phantasy Star Adventure (Japan)[tr en AGTP]
DELETE FROM game_gear_games WHERE id = 638; -- Phantasy Star Adventure (Japan)[tr en AGTP](Alt 1)
DELETE FROM game_gear_games WHERE id = 641; -- Phantasy Star Adventure (Japan)[tr en AGTP][v1.01]
DELETE FROM game_gear_games WHERE id = 642; -- Phantasy Star Adventure (Japan)[tr en]
DELETE FROM game_gear_games WHERE id = 643; -- Phantasy Star Adventure (Japan)[tr pt CBT](Alt 1)[pt-br]
DELETE FROM game_gear_games WHERE id = 647; -- Phantasy Star Gaiden (Japan)[tr en Magic_Trans][v1.0][Largefont]
DELETE FROM game_gear_games WHERE id = 648; -- Phantasy Star Gaiden (Japan)[tr en Magic_Trans][v1.0][Smallfont]
DELETE FROM game_gear_games WHERE id = 649; -- Phantasy Star Gaiden (Japan)[tr en Magic_Trans][v2.0][Largefont]
DELETE FROM game_gear_games WHERE id = 650; -- Phantasy Star Gaiden (Japan)[tr en Magic_Trans][v2.0][Smallfont]
DELETE FROM game_gear_games WHERE id = 651; -- Phantasy Star Gaiden (Japan)[tr en Magic_Trans][v3.0][Largefont]
DELETE FROM game_gear_games WHERE id = 652; -- Phantasy Star Gaiden (Japan)[tr en Magic_Trans][v3.0][Smallfont]
DELETE FROM game_gear_games WHERE id = 653; -- Phantasy Star Gaiden (Japan)[tr en Magic_Trans][v4.0][Smallfont]
DELETE FROM game_gear_games WHERE id = 669; -- Prince of Persia (Broderbund) (USA)[b2]
DELETE FROM game_gear_games WHERE id = 676; -- Psychic World (USA, Europe, Brazil) (En) (Rev 1)
DELETE FROM game_gear_games WHERE id = 677; -- Psychic World (USA, Europe, Brazil) (Rev 1)
DELETE FROM game_gear_games WHERE id = 682; -- Puyo Puyo (Japan) (En,Ja)
DELETE FROM game_gear_games WHERE id = 695; -- Revenge of Drancon (USA, Brazil)
DELETE FROM game_gear_games WHERE id = 694; -- Revenge of Drancon (USA, Brazil) (En)
DELETE FROM game_gear_games WHERE id = 696; -- Riddick Bowe Boxing (Japan) (En)
DELETE FROM game_gear_games WHERE id = 721; -- Scratch Golf (Japan)
DELETE FROM game_gear_games WHERE id = 738; -- Shining Force Gaiden - Final Conflict (Japan) (Virtual Console)
DELETE FROM game_gear_games WHERE id = 743; -- Shinobi (World) (Rev A)
DELETE FROM game_gear_games WHERE id = 742; -- Shinobi (World) (Rev A) (Virtual Console)
DELETE FROM game_gear_games WHERE id = 744; -- Shinobi II - The Silent Fury (USA, Europe)
DELETE FROM game_gear_games WHERE id = 753; -- Smurfs, The (Europe) (En,Fr,De,Es)
DELETE FROM game_gear_games WHERE id = 814; -- Sonic _ Tails (Japan) (En)
DELETE FROM game_gear_games WHERE id = 773; -- Sonic Labyrinth (World)
DELETE FROM game_gear_games WHERE id = 808; -- Sonic The Hedgehog - Triple Trouble (USA, Europe, Brazil) (En)
DELETE FROM game_gear_games WHERE id = 799; -- Sonic The Hedgehog (Japan, Europe, Brazil) (En) (Rev 1)
DELETE FROM game_gear_games WHERE id = 805; -- Sonic The Hedgehog (World) (Rev A)
DELETE FROM game_gear_games WHERE id = 804; -- Sonic The Hedgehog (World) (Rev A) (Virtual Console)
DELETE FROM game_gear_games WHERE id = 810; -- Sonic The Hedgehog 2 (USA) (Auto Demo)
DELETE FROM game_gear_games WHERE id = 823; -- Spider-Man - X-Men - Arcade''s Revenge (USA)
DELETE FROM game_gear_games WHERE id = 824; -- Sports Illustrated - Championship Football _ Baseball (Black Pearl Software - Unexpected Development)
DELETE FROM game_gear_games WHERE id = 875; -- Streets of Rage (World)
DELETE FROM game_gear_games WHERE id = 878; -- Striker (Europe) (En,Fr,De,Es,It)
DELETE FROM game_gear_games WHERE id = 892; -- Super Kick Off (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv)
DELETE FROM game_gear_games WHERE id = 900; -- Super Off Road Rev 1 [b2]
DELETE FROM game_gear_games WHERE id = 908; -- Surf Ninjas [b2]
DELETE FROM game_gear_games WHERE id = 910; -- Sylvan Tale (Japan)
DELETE FROM game_gear_games WHERE id = 911; -- Sylvan Tale (Japan)[h status music]
DELETE FROM game_gear_games WHERE id = 912; -- Sylvan Tale (Japan)[h status music][tr en AGTP][v1.00]
DELETE FROM game_gear_games WHERE id = 913; -- Sylvan Tale (Japan)[h status music][tr en AGTP][v1.01]
DELETE FROM game_gear_games WHERE id = 915; -- Sylvan Tale (Japan)[tr en AGTP][v1.01]
DELETE FROM game_gear_games WHERE id = 916; -- Sylvan Tale (Japan)[tr en]
DELETE FROM game_gear_games WHERE id = 924; -- Tails Adventure ~ Tails Adventures (en-ja)[b2]
DELETE FROM game_gear_games WHERE id = 925; -- Tails'' Skypatrol (JSH - Sega - Sims) (Japan)[tr pt]
DELETE FROM game_gear_games WHERE id = 927; -- Taisen Mahjong HaoPai (Japan)
DELETE FROM game_gear_games WHERE id = 930; -- Taito Chase H.Q. (Japan) (En)
DELETE FROM game_gear_games WHERE id = 937; -- Taz in Escape from Mars (USA, Europe)
DELETE FROM game_gear_games WHERE id = 956; -- Taz in Escape from Mars [t]
DELETE FROM game_gear_games WHERE id = 976; -- Tesserae Rev 1 (Eurocom - GameTek - Inline Design)
DELETE FROM game_gear_games WHERE id = 977; -- Tintin in Tibet (Europe) (En,Fr,De,Es,Nl,Sv)
DELETE FROM game_gear_games WHERE id = 980; -- Tom and Jerry - The Movie (Japan, Brazil)
DELETE FROM game_gear_games WHERE id = 981; -- Tom and Jerry - The Movie (USA, Europe) (En,Ja)
DELETE FROM game_gear_games WHERE id = 982; -- Tom and Jerry - The Movie [t +1 Mystic]
DELETE FROM game_gear_games WHERE id = 983; -- Tom and Jerry - The Movie [t +1]
DELETE FROM game_gear_games WHERE id = 986; -- Ultimate Soccer (Japan, Europe, Brazil) (En,Fr,De,Es,It)
DELETE FROM game_gear_games WHERE id = 989; -- Vampire - Master of Darkness (USA) (Virtual Console)
DELETE FROM game_gear_games WHERE id = 991; -- Vampire - Master of Darkness (USA)[t +1 Mystic]
DELETE FROM game_gear_games WHERE id = 997; -- Wakiyarando (Namco) (Japan) (Alt 1)
DELETE FROM game_gear_games WHERE id = 998; -- Wakiyarando (Namco) (Japan)[b2]
DELETE FROM game_gear_games WHERE id = 999; -- Wakiyarando (Namco) (Japan)[b3]
