# Script de renommage des images Game Gear kebab-case → Title Case
# Généré le 2026-02-18 19:45:55
# Total: 245 fichiers

Set-Location "C:\laragon\www\stock-R4E\public\images\taxonomy\gamegear"

Rename-Item -Path "adventures-of-batman-robin-the-Unknown-cover.png" -NewName "Adventures of Batman Robin the (World)-cover.png"
Rename-Item -Path "aladdin-Japan-cover.png" -NewName "Aladdin (Japan)-cover.png"
Rename-Item -Path "aladdin-Unknown-cover.png" -NewName "Aladdin (World)-cover.png"
Rename-Item -Path "alien-3-Japan-cover.png" -NewName "Alien 3 (Japan)-cover.png"
Rename-Item -Path "alien-3-Unknown-cover.png" -NewName "Alien 3 (World)-cover.png"
Rename-Item -Path "alien-syndrome-Japan-cover.png" -NewName "Alien Syndrome (Japan)-cover.png"
Rename-Item -Path "archer-macleans-dropzone-europe-artwork.png" -NewName "Archer Macleans Dropzone (Europe)-artwork.png"
Rename-Item -Path "archer-macleans-dropzone-europe-cover.png" -NewName "Archer Macleans Dropzone (Europe)-cover.png"
Rename-Item -Path "archer-macleans-dropzone-europe-gameplay.png" -NewName "Archer Macleans Dropzone (Europe)-gameplay.png"
Rename-Item -Path "asterix-and-the-great-rescue-europe-en-fr-de-es-it-artwork.png" -NewName "Asterix and the Great Rescue Europe En Fr De Es (It)-artwork.png"
Rename-Item -Path "asterix-and-the-great-rescue-europe-en-fr-de-es-it-cover.png" -NewName "Asterix and the Great Rescue Europe En Fr De Es (It)-cover.png"
Rename-Item -Path "asterix-and-the-great-rescue-europe-en-fr-de-es-it-gameplay.png" -NewName "Asterix and the Great Rescue Europe En Fr De Es (It)-gameplay.png"
Rename-Item -Path "asterix-and-the-secret-mission-europe-en-fr-de-artwork.png" -NewName "Asterix and the Secret Mission Europe En Fr (De)-artwork.png"
Rename-Item -Path "asterix-and-the-secret-mission-europe-en-fr-de-cover.png" -NewName "Asterix and the Secret Mission Europe En Fr (De)-cover.png"
Rename-Item -Path "asterix-and-the-secret-mission-europe-en-fr-de-gameplay.png" -NewName "Asterix and the Secret Mission Europe En Fr (De)-gameplay.png"
Rename-Item -Path "ax-battler-a-legend-of-golden-axe-v2-4-tr-es-pkt100%-cover.png" -NewName "Ax Battler a Legend of Golden Axe V2 4 Tr (Es)-cover.png"
Rename-Item -Path "ayrton-sennas-super-monaco-gp-ii-japan-artwork.png" -NewName "Ayrton Sennas Super Monaco Gp Ii (Japan)-artwork.png"
Rename-Item -Path "ayrton-sennas-super-monaco-gp-ii-japan-cover.png" -NewName "Ayrton Sennas Super Monaco Gp Ii (Japan)-cover.png"
Rename-Item -Path "ayrton-sennas-super-monaco-gp-ii-japan-gameplay.png" -NewName "Ayrton Sennas Super Monaco Gp Ii (Japan)-gameplay.png"
Rename-Item -Path "ayrton-sennas-super-monaco-gp-ii-usa-europe-brazil-artwork.png" -NewName "Ayrton Sennas Super Monaco Gp Ii Usa Europe (Brazil)-artwork.png"
Rename-Item -Path "ayrton-sennas-super-monaco-gp-ii-usa-europe-brazil-cover.png" -NewName "Ayrton Sennas Super Monaco Gp Ii Usa Europe (Brazil)-cover.png"
Rename-Item -Path "ayrton-sennas-super-monaco-gp-ii-usa-europe-brazil-en-artwork.png" -NewName "Ayrton Sennas Super Monaco Gp Ii Usa Europe Brazil (En)-artwork.png"
Rename-Item -Path "ayrton-sennas-super-monaco-gp-ii-usa-europe-brazil-en-cover.png" -NewName "Ayrton Sennas Super Monaco Gp Ii Usa Europe Brazil (En)-cover.png"
Rename-Item -Path "ayrton-sennas-super-monaco-gp-ii-usa-europe-brazil-en-gameplay.png" -NewName "Ayrton Sennas Super Monaco Gp Ii Usa Europe Brazil (En)-gameplay.png"
Rename-Item -Path "ayrton-sennas-super-monaco-gp-ii-usa-europe-brazil-gameplay.png" -NewName "Ayrton Sennas Super Monaco Gp Ii Usa Europe (Brazil)-gameplay.png"
Rename-Item -Path "berenstain-bears-camping-adventure-the-usa-artwork.png" -NewName "Berenstain Bears Camping Adventure the (USA)-artwork.png"
Rename-Item -Path "berenstain-bears-camping-adventure-the-usa-cover.png" -NewName "Berenstain Bears Camping Adventure the (USA)-cover.png"
Rename-Item -Path "berenstain-bears-camping-adventure-the-usa-gameplay.png" -NewName "Berenstain Bears Camping Adventure the (USA)-gameplay.png"
Rename-Item -Path "bonkers-wax-up-usa-europe-artwork.png" -NewName "Bonkers Wax Up Usa (Europe)-artwork.png"
Rename-Item -Path "bonkers-wax-up-usa-europe-cover.png" -NewName "Bonkers Wax Up Usa (Europe)-cover.png"
Rename-Item -Path "bonkers-wax-up-usa-europe-gameplay.png" -NewName "Bonkers Wax Up Usa (Europe)-gameplay.png"
Rename-Item -Path "bram-stokers-dracula-europe-artwork.png" -NewName "Bram Stokers Dracula (Europe)-artwork.png"
Rename-Item -Path "bram-stokers-dracula-europe-cover.png" -NewName "Bram Stokers Dracula (Europe)-cover.png"
Rename-Item -Path "bram-stokers-dracula-europe-gameplay.png" -NewName "Bram Stokers Dracula (Europe)-gameplay.png"
Rename-Item -Path "bram-stokers-dracula-usa-artwork.png" -NewName "Bram Stokers Dracula (USA)-artwork.png"
Rename-Item -Path "bram-stokers-dracula-usa-cover.png" -NewName "Bram Stokers Dracula (USA)-cover.png"
Rename-Item -Path "bram-stokers-dracula-usa-gameplay.png" -NewName "Bram Stokers Dracula (USA)-gameplay.png"
Rename-Item -Path "buster-fight-japan-en-ja-artwork.png" -NewName "Buster Fight Japan En (Ja)-artwork.png"
Rename-Item -Path "buster-fight-japan-en-ja-cover.png" -NewName "Buster Fight Japan En (Ja)-cover.png"
Rename-Item -Path "buster-fight-japan-en-ja-gameplay.png" -NewName "Buster Fight Japan En (Ja)-gameplay.png"
Rename-Item -Path "chase-h-q-usa-artwork.png" -NewName "Chase H Q (USA)-artwork.png"
Rename-Item -Path "chase-h-q-usa-cover.png" -NewName "Chase H Q (USA)-cover.png"
Rename-Item -Path "chase-h-q-usa-gameplay.png" -NewName "Chase H Q (USA)-gameplay.png"
Rename-Item -Path "cheese-cat-astrophe-starring-speedy-gonzales-usa-europe-brazil-en-fr-de-es-artwork.png" -NewName "Cheese Cat Astrophe Starring Speedy Gonzales Usa Europe Brazil En Fr De (Es)-artwork.png"
Rename-Item -Path "cheese-cat-astrophe-starring-speedy-gonzales-usa-europe-brazil-en-fr-de-es-cover.png" -NewName "Cheese Cat Astrophe Starring Speedy Gonzales Usa Europe Brazil En Fr De (Es)-cover.png"
Rename-Item -Path "cheese-cat-astrophe-starring-speedy-gonzales-usa-europe-brazil-en-fr-de-es-gameplay.png" -NewName "Cheese Cat Astrophe Starring Speedy Gonzales Usa Europe Brazil En Fr De (Es)-gameplay.png"
Rename-Item -Path "crayon-shin-chan-taiketsu-kantam-panic-japan-artwork.png" -NewName "Crayon Shin Chan Taiketsu Kantam Panic (Japan)-artwork.png"
Rename-Item -Path "crayon-shin-chan-taiketsu-kantam-panic-japan-cover.png" -NewName "Crayon Shin Chan Taiketsu Kantam Panic (Japan)-cover.png"
Rename-Item -Path "crayon-shin-chan-taiketsu-kantam-panic-japan-gameplay.png" -NewName "Crayon Shin Chan Taiketsu Kantam Panic (Japan)-gameplay.png"
Rename-Item -Path "crayon-shin-chan-taiketsu-kantam-panic-japan-t-en-by-psyklax-artwork.png" -NewName "Crayon Shin Chan Taiketsu Kantam Panic Japan T En By Psyklax-artwork.png"
Rename-Item -Path "crayon-shin-chan-taiketsu-kantam-panic-japan-t-en-by-psyklax-cover.png" -NewName "Crayon Shin Chan Taiketsu Kantam Panic Japan T En By Psyklax-cover.png"
Rename-Item -Path "daffy-duck-in-hollywood-europe-brazil-en-fr-de-es-it-artwork.png" -NewName "Daffy Duck in Hollywood Europe Brazil En Fr De Es (It)-artwork.png"
Rename-Item -Path "daffy-duck-in-hollywood-europe-brazil-en-fr-de-es-it-cover.png" -NewName "Daffy Duck in Hollywood Europe Brazil En Fr De Es (It)-cover.png"
Rename-Item -Path "daffy-duck-in-hollywood-europe-brazil-en-fr-de-es-it-gameplay.png" -NewName "Daffy Duck in Hollywood Europe Brazil En Fr De Es (It)-gameplay.png"
Rename-Item -Path "defenders-of-oasis-tr-fr-generation-ixv1-0-cover.png" -NewName "Defenders of Oasis Tr Fr Generation Ixv1 0-cover.png"
Rename-Item -Path "desert-speedtrap-starring-road-runner-and-wile-e-coyote-europe-en-fr-de-es-it-artwork.png" -NewName "Desert Speedtrap Starring Road Runner and Wile E Coyote Europe En Fr De Es (It)-artwork.png"
Rename-Item -Path "desert-speedtrap-starring-road-runner-and-wile-e-coyote-europe-en-fr-de-es-it-cover.png" -NewName "Desert Speedtrap Starring Road Runner and Wile E Coyote Europe En Fr De Es (It)-cover.png"
Rename-Item -Path "desert-speedtrap-starring-road-runner-and-wile-e-coyote-europe-en-fr-de-es-it-gameplay.png" -NewName "Desert Speedtrap Starring Road Runner and Wile E Coyote Europe En Fr De Es (It)-gameplay.png"
Rename-Item -Path "desert-speedtrap-starring-road-runner-and-wile-e-coyote-usa-brazil-cover.png" -NewName "Desert Speedtrap Starring Road Runner and Wile E Coyote Usa (Brazil)-cover.png"
Rename-Item -Path "desert-speedtrap-starring-road-runner-and-wile-e-coyote-usa-brazil-en-artwork.png" -NewName "Desert Speedtrap Starring Road Runner and Wile E Coyote Usa Brazil (En)-artwork.png"
Rename-Item -Path "desert-speedtrap-starring-road-runner-and-wile-e-coyote-usa-brazil-en-cover.png" -NewName "Desert Speedtrap Starring Road Runner and Wile E Coyote Usa Brazil (En)-cover.png"
Rename-Item -Path "desert-speedtrap-starring-road-runner-and-wile-e-coyote-usa-brazil-en-gameplay.png" -NewName "Desert Speedtrap Starring Road Runner and Wile E Coyote Usa Brazil (En)-gameplay.png"
Rename-Item -Path "desert-speedtrap-starring-road-runner-and-wile-e-coyote-usa-brazil-gameplay.png" -NewName "Desert Speedtrap Starring Road Runner and Wile E Coyote Usa (Brazil)-gameplay.png"
Rename-Item -Path "desert-strike-europe-en-fr-de-es-artwork.png" -NewName "Desert Strike Europe En Fr De (Es)-artwork.png"
Rename-Item -Path "desert-strike-europe-en-fr-de-es-cover.png" -NewName "Desert Strike Europe En Fr De (Es)-cover.png"
Rename-Item -Path "desert-strike-europe-en-fr-de-es-gameplay.png" -NewName "Desert Strike Europe En Fr De (Es)-gameplay.png"
Rename-Item -Path "donald-no-magical-world-japan-en-ja-artwork.png" -NewName "Donald No Magical World Japan En (Ja)-artwork.png"
Rename-Item -Path "donald-no-magical-world-japan-en-ja-cover.png" -NewName "Donald No Magical World Japan En (Ja)-cover.png"
Rename-Item -Path "donald-no-magical-world-japan-en-ja-gameplay.png" -NewName "Donald No Magical World Japan En (Ja)-gameplay.png"
Rename-Item -Path "dr-robotniks-mean-bean-machine-usa-europe-artwork.png" -NewName "Dr Robotniks Mean Bean Machine Usa (Europe)-artwork.png"
Rename-Item -Path "dr-robotniks-mean-bean-machine-usa-europe-cover.png" -NewName "Dr Robotniks Mean Bean Machine Usa (Europe)-cover.png"
Rename-Item -Path "dr-robotniks-mean-bean-machine-usa-europe-gameplay.png" -NewName "Dr Robotniks Mean Bean Machine Usa (Europe)-gameplay.png"
Rename-Item -Path "ernie-els-golf-europe-en-fr-de-es-it-artwork.png" -NewName "Ernie Els Golf Europe En Fr De Es (It)-artwork.png"
Rename-Item -Path "ernie-els-golf-europe-en-fr-de-es-it-cover.png" -NewName "Ernie Els Golf Europe En Fr De Es (It)-cover.png"
Rename-Item -Path "ernie-els-golf-europe-en-fr-de-es-it-gameplay.png" -NewName "Ernie Els Golf Europe En Fr De Es (It)-gameplay.png"
Rename-Item -Path "evander-holyfields-real-deal-boxing-usa-europe-artwork.png" -NewName "Evander Holyfields Real Deal Boxing Usa (Europe)-artwork.png"
Rename-Item -Path "evander-holyfields-real-deal-boxing-usa-europe-cover.png" -NewName "Evander Holyfields Real Deal Boxing Usa (Europe)-cover.png"
Rename-Item -Path "evander-holyfields-real-deal-boxing-usa-europe-gameplay.png" -NewName "Evander Holyfields Real Deal Boxing Usa (Europe)-gameplay.png"
Rename-Item -Path "fantastic-dizzy-usa-europe-en-fr-de-es-it-artwork.png" -NewName "Fantastic Dizzy Usa Europe En Fr De Es (It)-artwork.png"
Rename-Item -Path "fantastic-dizzy-usa-europe-en-fr-de-es-it-cover.png" -NewName "Fantastic Dizzy Usa Europe En Fr De Es (It)-cover.png"
Rename-Item -Path "fantastic-dizzy-usa-europe-en-fr-de-es-it-gameplay.png" -NewName "Fantastic Dizzy Usa Europe En Fr De Es (It)-gameplay.png"
Rename-Item -Path "fifa-soccer-96-usa-europe-en-fr-de-es-artwork.png" -NewName "Fifa Soccer 96 Usa Europe En Fr De (Es)-artwork.png"
Rename-Item -Path "fifa-soccer-96-usa-europe-en-fr-de-es-cover.png" -NewName "Fifa Soccer 96 Usa Europe En Fr De (Es)-cover.png"
Rename-Item -Path "fifa-soccer-96-usa-europe-en-fr-de-es-gameplay.png" -NewName "Fifa Soccer 96 Usa Europe En Fr De (Es)-gameplay.png"
Rename-Item -Path "galaga-91-japan-en-artwork.png" -NewName "Galaga 91 Japan (En)-artwork.png"
Rename-Item -Path "galaga-91-japan-en-cover.png" -NewName "Galaga 91 Japan (En)-cover.png"
Rename-Item -Path "galaga-91-japan-en-gameplay.png" -NewName "Galaga 91 Japan (En)-gameplay.png"
Rename-Item -Path "ganbare-gorby-japan-artwork.png" -NewName "Ganbare Gorby (Japan)-artwork.png"
Rename-Item -Path "ganbare-gorby-japan-cover.png" -NewName "Ganbare Gorby (Japan)-cover.png"
Rename-Item -Path "ganbare-gorby-japan-gameplay.png" -NewName "Ganbare Gorby (Japan)-gameplay.png"
Rename-Item -Path "george-foremans-ko-boxing-usa-europe-artwork.png" -NewName "George Foremans Ko Boxing Usa (Europe)-artwork.png"
Rename-Item -Path "george-foremans-ko-boxing-usa-europe-cover.png" -NewName "George Foremans Ko Boxing Usa (Europe)-cover.png"
Rename-Item -Path "george-foremans-ko-boxing-usa-europe-gameplay.png" -NewName "George Foremans Ko Boxing Usa (Europe)-gameplay.png"
Rename-Item -Path "greendog-the-beached-surfer-dude-usa-brazil-cover.png" -NewName "Greendog the Beached Surfer Dude Usa (Brazil)-cover.png"
Rename-Item -Path "greendog-the-beached-surfer-dude-usa-brazil-en-artwork.png" -NewName "Greendog the Beached Surfer Dude Usa Brazil (En)-artwork.png"
Rename-Item -Path "greendog-the-beached-surfer-dude-usa-brazil-en-cover.png" -NewName "Greendog the Beached Surfer Dude Usa Brazil (En)-cover.png"
Rename-Item -Path "greendog-the-beached-surfer-dude-usa-brazil-en-gameplay.png" -NewName "Greendog the Beached Surfer Dude Usa Brazil (En)-gameplay.png"
Rename-Item -Path "greendog-the-beached-surfer-dude-usa-brazil-gameplay.png" -NewName "Greendog the Beached Surfer Dude Usa (Brazil)-gameplay.png"
Rename-Item -Path "head-buster-japan-t-en-by-chris-m-covell-artwork.png" -NewName "Head Buster Japan T En By Chris M Covell-artwork.png"
Rename-Item -Path "head-buster-japan-t-en-by-chris-m-covell-cover.png" -NewName "Head Buster Japan T En By Chris M Covell-cover.png"
Rename-Item -Path "hyper-pro-yakyuu-92-japan-artwork.png" -NewName "Hyper Pro Yakyuu 92 (Japan)-artwork.png"
Rename-Item -Path "hyper-pro-yakyuu-92-japan-cover.png" -NewName "Hyper Pro Yakyuu 92 (Japan)-cover.png"
Rename-Item -Path "hyper-pro-yakyuu-92-japan-gameplay.png" -NewName "Hyper Pro Yakyuu 92 (Japan)-gameplay.png"
Rename-Item -Path "j-league-gg-pro-striker-94-japan-artwork.png" -NewName "J League Gg Pro Striker 94 (Japan)-artwork.png"
Rename-Item -Path "j-league-gg-pro-striker-94-japan-cover.png" -NewName "J League Gg Pro Striker 94 (Japan)-cover.png"
Rename-Item -Path "j-league-gg-pro-striker-94-japan-gameplay.png" -NewName "J League Gg Pro Striker 94 (Japan)-gameplay.png"
Rename-Item -Path "j-league-soccer-dream-eleven-japan-artwork.png" -NewName "J League Soccer Dream Eleven (Japan)-artwork.png"
Rename-Item -Path "j-league-soccer-dream-eleven-japan-cover.png" -NewName "J League Soccer Dream Eleven (Japan)-cover.png"
Rename-Item -Path "j-league-soccer-dream-eleven-japan-gameplay.png" -NewName "J League Soccer Dream Eleven (Japan)-gameplay.png"
Rename-Item -Path "jeopardy-sports-edition-usa-artwork.png" -NewName "Jeopardy Sports Edition (USA)-artwork.png"
Rename-Item -Path "jeopardy-sports-edition-usa-cover.png" -NewName "Jeopardy Sports Edition (USA)-cover.png"
Rename-Item -Path "jeopardy-sports-edition-usa-gameplay.png" -NewName "Jeopardy Sports Edition (USA)-gameplay.png"
Rename-Item -Path "jeopardy-usa-artwork.png" -NewName "Jeopardy (USA)-artwork.png"
Rename-Item -Path "jeopardy-usa-cover.png" -NewName "Jeopardy (USA)-cover.png"
Rename-Item -Path "jeopardy-usa-gameplay.png" -NewName "Jeopardy (USA)-gameplay.png"
Rename-Item -Path "krustys-fun-house-usa-europe-artwork.png" -NewName "Krustys Fun House Usa (Europe)-artwork.png"
Rename-Item -Path "krustys-fun-house-usa-europe-cover.png" -NewName "Krustys Fun House Usa (Europe)-cover.png"
Rename-Item -Path "krustys-fun-house-usa-europe-gameplay.png" -NewName "Krustys Fun House Usa (Europe)-gameplay.png"
Rename-Item -Path "madou-monogatari-i-3tsu-no-madoukyuu-compile-sega-japantr-en-matts-messy-roomv1-0-cover.png" -NewName "Madou Monogatari I 3tsu No Madoukyuu Compile Sega Japantr En Matts Messy Roomv1 0-cover.png"
Rename-Item -Path "man-overboard-europe-artwork.png" -NewName "Man Overboard (Europe)-artwork.png"
Rename-Item -Path "man-overboard-europe-cover.png" -NewName "Man Overboard (Europe)-cover.png"
Rename-Item -Path "man-overboard-europe-gameplay.png" -NewName "Man Overboard (Europe)-gameplay.png"
Rename-Item -Path "markos-magic-football-europe-en-fr-de-es-artwork.png" -NewName "Markos Magic Football Europe En Fr De (Es)-artwork.png"
Rename-Item -Path "markos-magic-football-europe-en-fr-de-es-cover.png" -NewName "Markos Magic Football Europe En Fr De (Es)-cover.png"
Rename-Item -Path "markos-magic-football-europe-en-fr-de-es-gameplay.png" -NewName "Markos Magic Football Europe En Fr De (Es)-gameplay.png"
Rename-Item -Path "mickeys-ultimate-challenge-usa-artwork.png" -NewName "Mickeys Ultimate Challenge (USA)-artwork.png"
Rename-Item -Path "mickeys-ultimate-challenge-usa-cover.png" -NewName "Mickeys Ultimate Challenge (USA)-cover.png"
Rename-Item -Path "mickeys-ultimate-challenge-usa-gameplay.png" -NewName "Mickeys Ultimate Challenge (USA)-gameplay.png"
Rename-Item -Path "ms-pac-man-usa-artwork.png" -NewName "Ms Pac Man (USA)-artwork.png"
Rename-Item -Path "ms-pac-man-usa-cover.png" -NewName "Ms Pac Man (USA)-cover.png"
Rename-Item -Path "ms-pac-man-usa-gameplay.png" -NewName "Ms Pac Man (USA)-gameplay.png"
Rename-Item -Path "neko-daisuki-japan-artwork.png" -NewName "Neko Daisuki (Japan)-artwork.png"
Rename-Item -Path "neko-daisuki-japan-cover.png" -NewName "Neko Daisuki (Japan)-cover.png"
Rename-Item -Path "neko-daisuki-japan-gameplay.png" -NewName "Neko Daisuki (Japan)-gameplay.png"
Rename-Item -Path "nfl-95-usa-artwork.png" -NewName "Nfl 95 (USA)-artwork.png"
Rename-Item -Path "nfl-95-usa-cover.png" -NewName "Nfl 95 (USA)-cover.png"
Rename-Item -Path "nfl-95-usa-gameplay.png" -NewName "Nfl 95 (USA)-gameplay.png"
Rename-Item -Path "ninku-japan-en-jatr-env0-1-cover.png" -NewName "Ninku Japan En Jatr Env0 1-cover.png"
Rename-Item -Path "olympic-gold-europe-en-fr-de-es-it-nl-pt-sv-artwork.png" -NewName "Olympic Gold Europe En Fr De Es It Nl (Pt)-artwork.png"
Rename-Item -Path "olympic-gold-europe-en-fr-de-es-it-nl-pt-sv-cover.png" -NewName "Olympic Gold Europe En Fr De Es It Nl (Pt)-cover.png"
Rename-Item -Path "olympic-gold-europe-en-fr-de-es-it-nl-pt-sv-gameplay.png" -NewName "Olympic Gold Europe En Fr De Es It Nl (Pt)-gameplay.png"
Rename-Item -Path "olympic-gold-japan-usa-brazil-en-fr-de-es-it-nl-pt-sv-artwork.png" -NewName "Olympic Gold Japan Usa Brazil En Fr De Es It Nl (Pt)-artwork.png"
Rename-Item -Path "olympic-gold-japan-usa-brazil-en-fr-de-es-it-nl-pt-sv-cover.png" -NewName "Olympic Gold Japan Usa Brazil En Fr De Es It Nl (Pt)-cover.png"
Rename-Item -Path "olympic-gold-japan-usa-brazil-en-fr-de-es-it-nl-pt-sv-gameplay.png" -NewName "Olympic Gold Japan Usa Brazil En Fr De Es It Nl (Pt)-gameplay.png"
Rename-Item -Path "olympic-gold-taiwan-en-fr-de-es-it-nl-pt-sv-unl-artwork.png" -NewName "Olympic Gold Taiwan En Fr De Es It Nl Pt Sv Unl-artwork.png"
Rename-Item -Path "olympic-gold-taiwan-en-fr-de-es-it-nl-pt-sv-unl-cover.png" -NewName "Olympic Gold Taiwan En Fr De Es It Nl Pt Sv Unl-cover.png"
Rename-Item -Path "olympic-gold-taiwan-en-fr-de-es-it-nl-pt-sv-unl-gameplay.png" -NewName "Olympic Gold Taiwan En Fr De Es It Nl Pt Sv Unl-gameplay.png"
Rename-Item -Path "ottifants-the-europe-en-fr-de-es-it-artwork.png" -NewName "Ottifants the Europe En Fr De Es (It)-artwork.png"
Rename-Item -Path "ottifants-the-europe-en-fr-de-es-it-cover.png" -NewName "Ottifants the Europe En Fr De Es (It)-cover.png"
Rename-Item -Path "ottifants-the-europe-en-fr-de-es-it-gameplay.png" -NewName "Ottifants the Europe En Fr De Es (It)-gameplay.png"
Rename-Item -Path "out-run-europa-probe-sega-u-s-gold-usatr-pt-cover.png" -NewName "Out Run Europa Probe Sega U S Gold Usatr (Pt)-cover.png"
Rename-Item -Path "pet-club-inu-daisuki-japan-artwork.png" -NewName "Pet Club Inu Daisuki (Japan)-artwork.png"
Rename-Item -Path "pet-club-inu-daisuki-japan-cover.png" -NewName "Pet Club Inu Daisuki (Japan)-cover.png"
Rename-Item -Path "pet-club-inu-daisuki-japan-gameplay.png" -NewName "Pet Club Inu Daisuki (Japan)-gameplay.png"
Rename-Item -Path "poker-face-pauls-blackjack-usa-artwork.png" -NewName "Poker Face Pauls Blackjack (USA)-artwork.png"
Rename-Item -Path "poker-face-pauls-blackjack-usa-cover.png" -NewName "Poker Face Pauls Blackjack (USA)-cover.png"
Rename-Item -Path "poker-face-pauls-blackjack-usa-gameplay.png" -NewName "Poker Face Pauls Blackjack (USA)-gameplay.png"
Rename-Item -Path "poker-face-pauls-gin-usa-artwork.png" -NewName "Poker Face Pauls Gin (USA)-artwork.png"
Rename-Item -Path "poker-face-pauls-gin-usa-cover.png" -NewName "Poker Face Pauls Gin (USA)-cover.png"
Rename-Item -Path "poker-face-pauls-gin-usa-gameplay.png" -NewName "Poker Face Pauls Gin (USA)-gameplay.png"
Rename-Item -Path "poker-face-pauls-poker-usa-artwork.png" -NewName "Poker Face Pauls Poker (USA)-artwork.png"
Rename-Item -Path "poker-face-pauls-poker-usa-cover.png" -NewName "Poker Face Pauls Poker (USA)-cover.png"
Rename-Item -Path "poker-face-pauls-poker-usa-gameplay.png" -NewName "Poker Face Pauls Poker (USA)-gameplay.png"
Rename-Item -Path "poker-face-pauls-solitaire-usa-artwork.png" -NewName "Poker Face Pauls Solitaire (USA)-artwork.png"
Rename-Item -Path "poker-face-pauls-solitaire-usa-cover.png" -NewName "Poker Face Pauls Solitaire (USA)-cover.png"
Rename-Item -Path "poker-face-pauls-solitaire-usa-gameplay.png" -NewName "Poker Face Pauls Solitaire (USA)-gameplay.png"
Rename-Item -Path "pro-yakyuu-91-the-japan-artwork.png" -NewName "Pro Yakyuu 91 the (Japan)-artwork.png"
Rename-Item -Path "pro-yakyuu-91-the-japan-cover.png" -NewName "Pro Yakyuu 91 the (Japan)-cover.png"
Rename-Item -Path "pro-yakyuu-91-the-japan-gameplay.png" -NewName "Pro Yakyuu 91 the (Japan)-gameplay.png"
Rename-Item -Path "pro-yakyuu-gg-league-94-japan-artwork.png" -NewName "Pro Yakyuu Gg League 94 (Japan)-artwork.png"
Rename-Item -Path "pro-yakyuu-gg-league-94-japan-cover.png" -NewName "Pro Yakyuu Gg League 94 (Japan)-cover.png"
Rename-Item -Path "pro-yakyuu-gg-league-94-japan-gameplay.png" -NewName "Pro Yakyuu Gg League 94 (Japan)-gameplay.png"
Rename-Item -Path "puyo-puyo-japan-en-ja-artwork.png" -NewName "Puyo Puyo Japan En (Ja)-artwork.png"
Rename-Item -Path "puyo-puyo-japan-en-ja-cover.png" -NewName "Puyo Puyo Japan En (Ja)-cover.png"
Rename-Item -Path "puyo-puyo-japan-en-ja-gameplay.png" -NewName "Puyo Puyo Japan En (Ja)-gameplay.png"
Rename-Item -Path "quiz-gear-fight-the-japan-artwork.png" -NewName "Quiz Gear Fight the (Japan)-artwork.png"
Rename-Item -Path "quiz-gear-fight-the-japan-cover.png" -NewName "Quiz Gear Fight the (Japan)-cover.png"
Rename-Item -Path "quiz-gear-fight-the-japan-gameplay.png" -NewName "Quiz Gear Fight the (Japan)-gameplay.png"
Rename-Item -Path "r-b-i-baseball-94-usa-artwork.png" -NewName "R B I Baseball 94 (USA)-artwork.png"
Rename-Item -Path "r-b-i-baseball-94-usa-cover.png" -NewName "R B I Baseball 94 (USA)-cover.png"
Rename-Item -Path "r-b-i-baseball-94-usa-gameplay.png" -NewName "R B I Baseball 94 (USA)-gameplay.png"
Rename-Item -Path "r-c-grand-prix-usa-artwork.png" -NewName "R C Grand Prix (USA)-artwork.png"
Rename-Item -Path "r-c-grand-prix-usa-cover.png" -NewName "R C Grand Prix (USA)-cover.png"
Rename-Item -Path "r-c-grand-prix-usa-gameplay.png" -NewName "R C Grand Prix (USA)-gameplay.png"
Rename-Item -Path "sassou-shounen-eiyuuden-coca-cola-kid-japantr-en-sms-powerv1-00-cover.png" -NewName "Sassou Shounen Eiyuuden Coca Cola Kid Japantr En Sms Powerv1 00-cover.png"
Rename-Item -Path "schtroumpfs-autour-du-monde-les-europe-en-fr-de-es-artwork.png" -NewName "Schtroumpfs Autour Du Monde Les Europe En Fr De (Es)-artwork.png"
Rename-Item -Path "schtroumpfs-autour-du-monde-les-europe-en-fr-de-es-cover.png" -NewName "Schtroumpfs Autour Du Monde Les Europe En Fr De (Es)-cover.png"
Rename-Item -Path "sd-gundam-winners-history-japan-artwork.png" -NewName "Sd Gundam Winners History (Japan)-artwork.png"
Rename-Item -Path "sd-gundam-winners-history-japan-cover.png" -NewName "Sd Gundam Winners History (Japan)-cover.png"
Rename-Item -Path "sd-gundam-winners-history-japan-gameplay.png" -NewName "Sd Gundam Winners History (Japan)-gameplay.png"
Rename-Item -Path "sd-gundam-winners-history-japan-t-en-by-gaijin-productions-artwork.png" -NewName "Sd Gundam Winners History Japan T En By Gaijin Productions-artwork.png"
Rename-Item -Path "sd-gundam-winners-history-japan-t-en-by-gaijin-productions-cover.png" -NewName "Sd Gundam Winners History Japan T En By Gaijin Productions-cover.png"
Rename-Item -Path "simpsons-the-bart-vs-the-space-mutants-usa-europe-artwork.png" -NewName "Simpsons the Bart Vs the Space Mutants Usa (Europe)-artwork.png"
Rename-Item -Path "simpsons-the-bart-vs-the-space-mutants-usa-europe-cover.png" -NewName "Simpsons the Bart Vs the Space Mutants Usa (Europe)-cover.png"
Rename-Item -Path "simpsons-the-bart-vs-the-space-mutants-usa-europe-gameplay.png" -NewName "Simpsons the Bart Vs the Space Mutants Usa (Europe)-gameplay.png"
Rename-Item -Path "simpsons-the-bart-vs-the-world-world-artwork.png" -NewName "Simpsons the Bart Vs the World (World)-artwork.png"
Rename-Item -Path "simpsons-the-bart-vs-the-world-world-cover.png" -NewName "Simpsons the Bart Vs the World (World)-cover.png"
Rename-Item -Path "simpsons-the-bart-vs-the-world-world-gameplay.png" -NewName "Simpsons the Bart Vs the World (World)-gameplay.png"
Rename-Item -Path "smurfs-the-europe-en-fr-de-es-artwork.png" -NewName "Smurfs the Europe En Fr De (Es)-artwork.png"
Rename-Item -Path "smurfs-the-europe-en-fr-de-es-cover.png" -NewName "Smurfs the Europe En Fr De (Es)-cover.png"
Rename-Item -Path "smurfs-the-europe-en-fr-de-es-gameplay.png" -NewName "Smurfs the Europe En Fr De (Es)-gameplay.png"
Rename-Item -Path "smurfs-travel-the-world-the-europe-en-fr-de-es-artwork.png" -NewName "Smurfs Travel the World the Europe En Fr De (Es)-artwork.png"
Rename-Item -Path "smurfs-travel-the-world-the-europe-en-fr-de-es-gameplay.png" -NewName "Smurfs Travel the World the Europe En Fr De (Es)-gameplay.png"
Rename-Item -Path "striker-europe-en-fr-de-es-it-artwork.png" -NewName "Striker Europe En Fr De Es (It)-artwork.png"
Rename-Item -Path "striker-europe-en-fr-de-es-it-cover.png" -NewName "Striker Europe En Fr De Es (It)-cover.png"
Rename-Item -Path "striker-europe-en-fr-de-es-it-gameplay.png" -NewName "Striker Europe En Fr De Es (It)-gameplay.png"
Rename-Item -Path "super-kick-off-europe-en-fr-de-es-it-nl-pt-sv-artwork.png" -NewName "Super Kick Off Europe En Fr De Es It Nl (Pt)-artwork.png"
Rename-Item -Path "super-kick-off-europe-en-fr-de-es-it-nl-pt-sv-cover.png" -NewName "Super Kick Off Europe En Fr De Es It Nl (Pt)-cover.png"
Rename-Item -Path "super-kick-off-europe-en-fr-de-es-it-nl-pt-sv-gameplay.png" -NewName "Super Kick Off Europe En Fr De Es It Nl (Pt)-gameplay.png"
Rename-Item -Path "super-smash-t-v-world-artwork.png" -NewName "Super Smash T V (World)-artwork.png"
Rename-Item -Path "super-smash-t-v-world-cover.png" -NewName "Super Smash T V (World)-cover.png"
Rename-Item -Path "super-smash-t-v-world-gameplay.png" -NewName "Super Smash T V (World)-gameplay.png"
Rename-Item -Path "sylvan-tale-japantr-fr-asmodeathv0-9-cover.png" -NewName "Sylvan Tale Japantr Fr Asmodeathv0 9-cover.png"
Rename-Item -Path "tails-adventure-world-en-ja-artwork.png" -NewName "Tails Adventure World En (Ja)-artwork.png"
Rename-Item -Path "tails-adventure-world-en-ja-cover.png" -NewName "Tails Adventure World En (Ja)-cover.png"
Rename-Item -Path "tails-adventure-world-en-ja-gameplay.png" -NewName "Tails Adventure World En (Ja)-gameplay.png"
Rename-Item -Path "tails-adventure-world-en-ja-virtual-console-artwork.png" -NewName "Tails Adventure World En Ja Virtual Console-artwork.png"
Rename-Item -Path "tails-adventure-world-en-ja-virtual-console-cover.png" -NewName "Tails Adventure World En Ja Virtual Console-cover.png"
Rename-Item -Path "tails-adventure-world-en-ja-virtual-console-gameplay.png" -NewName "Tails Adventure World En Ja Virtual Console-gameplay.png"
Rename-Item -Path "tails-skypatrol-japan-en-artwork.png" -NewName "Tails Skypatrol Japan (En)-artwork.png"
Rename-Item -Path "tails-skypatrol-japan-en-cover.png" -NewName "Tails Skypatrol Japan (En)-cover.png"
Rename-Item -Path "tails-skypatrol-japan-en-gameplay.png" -NewName "Tails Skypatrol Japan (En)-gameplay.png"
Rename-Item -Path "tails-skypatrol-jsh-sega-sims-japantr-pt-cover.png" -NewName "Tails Skypatrol Jsh Sega Sims Japantr (Pt)-cover.png"
Rename-Item -Path "taito-chase-h-q-japan-en-artwork.png" -NewName "Taito Chase H Q Japan (En)-artwork.png"
Rename-Item -Path "taito-chase-h-q-japan-en-cover.png" -NewName "Taito Chase H Q Japan (En)-cover.png"
Rename-Item -Path "taito-chase-h-q-japan-en-gameplay.png" -NewName "Taito Chase H Q Japan (En)-gameplay.png"
Rename-Item -Path "tatakae-pro-yakyuu-twin-league-japan-artwork.png" -NewName "Tatakae Pro Yakyuu Twin League (Japan)-artwork.png"
Rename-Item -Path "tatakae-pro-yakyuu-twin-league-japan-cover.png" -NewName "Tatakae Pro Yakyuu Twin League (Japan)-cover.png"
Rename-Item -Path "tatakae-pro-yakyuu-twin-league-japan-gameplay.png" -NewName "Tatakae Pro Yakyuu Twin League (Japan)-gameplay.png"
Rename-Item -Path "tempo-jr-world-artwork.png" -NewName "Tempo Jr (World)-artwork.png"
Rename-Item -Path "tempo-jr-world-cover.png" -NewName "Tempo Jr (World)-cover.png"
Rename-Item -Path "tempo-jr-world-gameplay.png" -NewName "Tempo Jr (World)-gameplay.png"
Rename-Item -Path "tintin-in-tibet-europe-en-fr-de-es-nl-sv-artwork.png" -NewName "Tintin in Tibet Europe En Fr De Es Nl Sv-artwork.png"
Rename-Item -Path "tintin-in-tibet-europe-en-fr-de-es-nl-sv-cover.png" -NewName "Tintin in Tibet Europe En Fr De Es Nl Sv-cover.png"
Rename-Item -Path "tintin-in-tibet-europe-en-fr-de-es-nl-sv-gameplay.png" -NewName "Tintin in Tibet Europe En Fr De Es Nl Sv-gameplay.png"
Rename-Item -Path "tom-and-jerry-the-movie-japan-brazil-en-ja-artwork.png" -NewName "Tom and Jerry the Movie Japan Brazil En (Ja)-artwork.png"
Rename-Item -Path "tom-and-jerry-the-movie-japan-brazil-en-ja-cover.png" -NewName "Tom and Jerry the Movie Japan Brazil En (Ja)-cover.png"
Rename-Item -Path "tom-and-jerry-the-movie-japan-brazil-en-ja-gameplay.png" -NewName "Tom and Jerry the Movie Japan Brazil En (Ja)-gameplay.png"
Rename-Item -Path "tom-and-jerry-the-movie-usa-europe-en-ja-artwork.png" -NewName "Tom and Jerry the Movie Usa Europe En (Ja)-artwork.png"
Rename-Item -Path "tom-and-jerry-the-movie-usa-europe-en-ja-cover.png" -NewName "Tom and Jerry the Movie Usa Europe En (Ja)-cover.png"
Rename-Item -Path "tom-and-jerry-the-movie-usa-europe-en-ja-gameplay.png" -NewName "Tom and Jerry the Movie Usa Europe En (Ja)-gameplay.png"
Rename-Item -Path "ultimate-soccer-japan-europe-brazil-en-fr-de-es-it-artwork.png" -NewName "Ultimate Soccer Japan Europe Brazil En Fr De Es (It)-artwork.png"
Rename-Item -Path "ultimate-soccer-japan-europe-brazil-en-fr-de-es-it-cover.png" -NewName "Ultimate Soccer Japan Europe Brazil En Fr De Es (It)-cover.png"
Rename-Item -Path "ultimate-soccer-japan-europe-brazil-en-fr-de-es-it-gameplay.png" -NewName "Ultimate Soccer Japan Europe Brazil En Fr De Es (It)-gameplay.png"
